apiVersion: v1
kind: Pod
metadata:
  name: goproxy
  labels:
    app: goproxy
spec:
  containers:
  - name: goproxy
    image: k8s.gcr.io/goproxy:0.1
    ports:
    - containerPort: 8080
    # Uses both readiness and liveness
    readinessProbe: # Attempts to connect to the goproxy container on port 8080
      tcpSocket: # If probe succeeds, the pod will be marked as ready, otherwise it won't receive traffic
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe: # If liveness probe fails the container will be restarted
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20